import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { OnderhoudComponent } from './onderhoud/onderhoud.component';
import { ConfigComponent } from './onderhoud/config/config.component';
import { SpelsoortenComponent } from './onderhoud/spelsoorten/spelsoorten.component';
import { VerenigingenComponent } from './onderhoud/verenigingen/verenigingen.component';
import { SpelersComponent } from './onderhoud/spelers/spelers.component';
import { SpelerComponent } from './onderhoud/spelers/speler/speler.component';
import { VerenigingComponent } from './onderhoud/verenigingen/vereniging/vereniging.component';
import { VerenigingAddComponent } from './onderhoud/verenigingen/vereniging/vereniging-add/vereniging-add.component';
import { VerenigingEditComponent } from './onderhoud/verenigingen/vereniging/vereniging-edit/vereniging-edit.component';
import { VerenigingTeamComponent } from './onderhoud/verenigingen/vereniging/vereniging-team/vereniging-team.component';
import { MoyenneTabellenComponent } from './onderhoud/moyenne-tabellen/moyenne-tabellen.component';
import { MoyenneTabelEditComponent } from './onderhoud/moyenne-tabellen/moyenne-tabel-edit/moyenne-tabel-edit.component';
import { MoyenneTabelAddComponent } from './onderhoud/moyenne-tabellen/moyenne-tabel-add/moyenne-tabel-add.component';
import { KnbbCompetitiesComponent } from './onderhoud/knbb-competities/knbb-competities.component';
import { KnbbDistrictenComponent } from './onderhoud/knbb-districten/knbb-districten.component';
import { KnbbCompetitieAddComponent } from './onderhoud/knbb-competities/knbb-competitie-add/knbb-competitie-add.component';
import { KnbbCompetitieEditComponent } from './onderhoud/knbb-competities/knbb-competitie-edit/knbb-competitie-edit.component';
import { KnbbCompetitieEditTeamsComponent } from './onderhoud/knbb-competities/knbb-competitie-edit-teams/knbb-competitie-edit-teams.component';
import { SpelkeuzeComponent } from './spelen/spelkeuze/spelkeuze.component';
import { WedstrijdComponent } from './spelen/wedstrijd/wedstrijd.component';
import { WedSpelersComponent } from './spelen/wedstrijd/wed-spelers/wed-spelers.component';
import { WedConfigComponent } from './spelen/wedstrijd/wed-config/wed-config.component';
import { WedScoreComponent } from './spelen/wedstrijd/wed-score/wed-score.component';
import { KnbbTeamMatchComponent } from './spelen/knbb-team-match/knbb-team-match.component';
import { KnbbTeamMatchScoreComponent } from './spelen/knbb-team-match/knbb-team-match-score/knbb-team-match-score.component';
import { KnbbTeamMatchSetupComponent } from './spelen/knbb-team-match/knbb-team-match-setup/knbb-team-match-setup.component';
import { KnbbTeamMatchCheckComponent } from './spelen/knbb-team-match/knbb-team-match-check/knbb-team-match-check.component';
import { KnbbTeamMatchCompComponent } from './spelen/knbb-team-match/knbb-team-match-comp/knbb-team-match-comp.component';
import { WedAantSpelersComponent } from './spelen/wedstrijd/wed-aant-spelers/wed-aant-spelers.component';
import { KnbbTeamMatchLijstComponent } from './spelen/knbb-team-match/knbb-team-match-lijst/knbb-team-match-lijst.component';
import { WedLijstComponent } from './spelen/wedstrijd/wed-lijst/wed-lijst.component';
import { LoginComponent } from './login/login.component';
import { KnbbMatchComponent } from './spelen/knbb-match/knbb-match.component';
import { KnbbMatchCompComponent } from './spelen/knbb-match/knbb-match-comp/knbb-match-comp.component';
import { KnbbMatchSetupComponent } from './spelen/knbb-match/knbb-match-setup/knbb-match-setup.component';
import { KnbbMatchCheckComponent } from './spelen/knbb-match/knbb-match-check/knbb-match-check.component';
import { KnbbMatchScoreComponent } from './spelen/knbb-match/knbb-match-score/knbb-match-score.component';
import { KnbbMatchLijstComponent } from './spelen/knbb-match/knbb-match-lijst/knbb-match-lijst.component';
import { BpCompetitiesComponent } from './bpoint/bp-competities/bp-competities.component';
import { BpHomeComponent } from './bpoint/bp-home/bp-home.component';
import { BpDistrictenComponent } from './bpoint/bp-districten/bp-districten.component';
import { BpDistrictComponent } from './bpoint/bp-districten/bp-district/bp-district.component';
import { BpMoyennesComponent } from './bpoint/bp-moyennes/bp-moyennes.component';
import { BpCompetitieComponent } from './bpoint/bp-competities/bp-competitie/bp-competitie.component';
import { BpCompetitieTeamComponent } from './bpoint/bp-competities/bp-competitie/bp-competitie-team/bp-competitie-team.component';
import { ErrorPageComponent } from './error-page/error-page.component';

export const routes: Routes = [
    { path: 'login', component: LoginComponent },
    { path: 'home', component: HomeComponent },
    { path: 'match/lijst/:wedNr', component: KnbbMatchLijstComponent },
    { path: 'match/lijst', component: KnbbMatchLijstComponent },
    { path: 'match/setup/spelers', component: KnbbMatchSetupComponent },
    { path: 'match/setup/comp', component: KnbbMatchCompComponent },
    { path: 'match/setup/check', component: KnbbMatchCheckComponent },
    { path: 'match/score', component: KnbbMatchScoreComponent },
    { path: 'match', component: KnbbMatchComponent },
    { path: 'teammatch/lijst', component: KnbbTeamMatchLijstComponent },
    { path: 'teammatch/setup', children: [
        { path: 'thuis', component: KnbbTeamMatchSetupComponent },
        { path: 'gasten', component: KnbbTeamMatchSetupComponent }
    ]},
    { path: 'teammatch/setup/comp', component: KnbbTeamMatchCompComponent },
    { path: 'teammatch/setup/check', component: KnbbTeamMatchCheckComponent },
    { path: 'teammatch/score/:wedNr', component: KnbbTeamMatchScoreComponent },
    { path: 'teammatch', component: KnbbTeamMatchComponent },
    { path: 'onderhoud/verenigingen/toevoegen', component: VerenigingAddComponent },
    { path: 'onderhoud/verenigingen/:verId/team/:teamId', component: VerenigingTeamComponent },
    { path: 'onderhoud/verenigingen/:verId/edit', component: VerenigingEditComponent },
    { path: 'onderhoud/verenigingen/:verId/spelers', component: SpelersComponent },
    { path: 'onderhoud/verenigingen/:verId', component: VerenigingComponent },
    { path: 'onderhoud/verenigingen', component: VerenigingenComponent },
    { path: 'onderhoud/spelers/toevoegen/:verId', component: SpelerComponent },
    { path: 'onderhoud/spelers/toevoegen', component: SpelerComponent },
    { path: 'onderhoud/spelers/:spelerId', component: SpelerComponent },
    { path: 'onderhoud/spelers', component: SpelersComponent },
    { path: 'onderhoud/knbbcompetities/toevoegen', component: KnbbCompetitieAddComponent },
    { path: 'onderhoud/knbbcompetities/:compId/teams', component: KnbbCompetitieEditTeamsComponent },
    { path: 'onderhoud/knbbcompetities/:compId', component: KnbbCompetitieEditComponent },
    { path: 'onderhoud/knbbcompetities', component: KnbbCompetitiesComponent },
    { path: 'onderhoud/moyennes/toevoegen', component: MoyenneTabelAddComponent },
    { path: 'onderhoud/moyennes/:klasse', component: MoyenneTabelEditComponent },
    { path: 'onderhoud/moyennes', component: MoyenneTabellenComponent },
    { path: 'onderhoud/districten', component: KnbbDistrictenComponent },
    { path: 'onderhoud/spelsoorten', component: SpelsoortenComponent },
    { path: 'onderhoud/instellingen', component: ConfigComponent },
    { path: 'onderhoud', component: OnderhoudComponent },
    { path: 'spelkeuze', component: SpelkeuzeComponent },
    { path: 'wedstrijd/score', component: WedScoreComponent },
    { path: 'wedstrijd/config', component: WedConfigComponent },
    { path: 'wedstrijd/lijst', component: WedLijstComponent },
    { path: 'wedstrijd/spelers', component: WedSpelersComponent },
    { path: 'wedstrijd/aantspl', component: WedAantSpelersComponent },
    { path: 'wedstrijd', component: WedstrijdComponent },
    { path: 'bpoint/home', component: BpHomeComponent },
    { path: 'bpoint/districten', component: BpDistrictenComponent },
    { path: 'bpoint/district', component: BpDistrictComponent },
    { path: 'bpoint/competitie', component: BpCompetitieComponent },
    { path: 'bpoint/competities', component: BpCompetitiesComponent },
    { path: 'bpoint/compteam', component: BpCompetitieTeamComponent },
    { path: 'bpoint/moyennes', component: BpMoyennesComponent },
    { path: 'error/:condition', component: ErrorPageComponent },
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: '**', redirectTo: 'home', pathMatch: 'full' }
];
