import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { OnderhoudComponent } from './onderhoud/onderhoud.component';
import { ConfigComponent } from './onderhoud/config/config.component';
import { SpelsoortenComponent } from './onderhoud/spelsoorten/spelsoorten.component';
import { VerenigingenComponent } from './onderhoud/verenigingen/verenigingen.component';
import { SpelersComponent } from './onderhoud/spelers/spelers.component';
import { SpelerComponent } from './onderhoud/spelers/speler/speler.component';
import { VerenigingComponent } from './onderhoud/verenigingen/vereniging/vereniging.component';
import { VerenigingAddComponent } from './onderhoud/verenigingen/vereniging/vereniging-add/vereniging-add.component';
import { VerenigingEditComponent } from './onderhoud/verenigingen/vereniging/vereniging-edit/vereniging-edit.component';
import { VerenigingTeamComponent } from './onderhoud/verenigingen/vereniging/vereniging-team/vereniging-team.component';
import { MoyenneTabellenComponent } from './onderhoud/moyenne-tabellen/moyenne-tabellen.component';
import { MoyenneTabelEditComponent } from './onderhoud/moyenne-tabellen/moyenne-tabel-edit/moyenne-tabel-edit.component';
import { MoyenneTabelAddComponent } from './onderhoud/moyenne-tabellen/moyenne-tabel-add/moyenne-tabel-add.component';
import { KnbbCompetitiesComponent } from './onderhoud/knbb-competities/knbb-competities.component';
import { KnbbDistrictenComponent } from './onderhoud/knbb-districten/knbb-districten.component';
import { KnbbCompetitieAddComponent } from './onderhoud/knbb-competities/knbb-competitie-add/knbb-competitie-add.component';
import { KnbbCompetitieEditComponent } from './onderhoud/knbb-competities/knbb-competitie-edit/knbb-competitie-edit.component';
import { KnbbCompetitieEditTeamsComponent } from './onderhoud/knbb-competities/knbb-competitie-edit-teams/knbb-competitie-edit-teams.component';
import { SpelkeuzeComponent } from './spelen/spelkeuze/spelkeuze.component';
import { WedstrijdComponent } from './spelen/wedstrijd/wedstrijd.component';
import { WedSpelersComponent } from './spelen/wedstrijd/wed-spelers/wed-spelers.component';
import { WedConfigComponent } from './spelen/wedstrijd/wed-config/wed-config.component';
import { KnbbTeamMatchComponent } from './spelen/knbb-team-match/knbb-team-match.component';
import { KnbbTeamMatchSetupComponent } from './spelen/knbb-team-match/knbb-team-match-setup/knbb-team-match-setup.component';
import { KnbbTeamMatchCheckComponent } from './spelen/knbb-team-match/knbb-team-match-check/knbb-team-match-check.component';
import { KnbbTeamMatchCompComponent } from './spelen/knbb-team-match/knbb-team-match-comp/knbb-team-match-comp.component';
import { WedAantSpelersComponent } from './spelen/wedstrijd/wed-aant-spelers/wed-aant-spelers.component';
import { KnbbTeamMatchLijstComponent } from './spelen/knbb-team-match/knbb-team-match-lijst/knbb-team-match-lijst.component';
import { WedLijstComponent } from './spelen/wedstrijd/wed-lijst/wed-lijst.component';
import { LoginComponent } from './login/login.component';
import { KnbbMatchComponent } from './spelen/knbb-match/knbb-match.component';
import { KnbbMatchCompComponent } from './spelen/knbb-match/knbb-match-comp/knbb-match-comp.component';
import { KnbbMatchSetupComponent } from './spelen/knbb-match/knbb-match-setup/knbb-match-setup.component';
import { KnbbMatchCheckComponent } from './spelen/knbb-match/knbb-match-check/knbb-match-check.component';
import { KnbbMatchLijstComponent } from './spelen/knbb-match/knbb-match-lijst/knbb-match-lijst.component';
import { BpHomeComponent } from './biljartpoint/bp-home/bp-home.component';
import { BpDistrictenComponent } from './biljartpoint/bp-districten/bp-districten.component';
import { BpDistrictComponent } from './biljartpoint/bp-districten/bp-district/bp-district.component';
import { BpMoyennesComponent } from './biljartpoint/bp-moyennes/bp-moyennes.component';
import { ErrorPageComponent } from './error-page/error-page.component';
import { LokaliteitenComponent } from './onderhoud/lokaliteiten/lokaliteiten.component';
import { LokaliteitComponent } from './onderhoud/lokaliteiten/lokaliteit/lokaliteit.component';
import { BpCompetitiesComponent } from './biljartpoint/bp-competities/bp-competities.component';
import { BpCompetitieComponent } from './biljartpoint/bp-competitie/bp-competitie.component';
import { BpCompetitieTeamsComponent } from './biljartpoint/bp-competitie-teams/bp-competitie-teams.component';
import { BpLokaliteitComponent } from './biljartpoint/bp-competitie-team/bp-lokaliteit/bp-lokaliteit.component';
import { BpVerenigingComponent } from './biljartpoint/bp-competitie-team/bp-vereniging/bp-vereniging.component';
import { BpSpelersComponent } from './biljartpoint/bp-competitie-team/bp-spelers/bp-spelers.component';
import { CompetitiesComponent } from './onderhoud/eigen/competities/competities.component';
import { CompetitieComponent } from './onderhoud/eigen/competitie/competitie.component';
import { CompSpelersComponent } from './onderhoud/eigen/comp-spelers/comp-spelers.component';
import { EigenCompetitiesComponent } from './spelen/eigen/eigen-competities/eigen-competities.component';
import { EigenCompetitieComponent } from './spelen/eigen/eigen-competitie/eigen-competitie.component';
import { EigenCompetitieSpelerComponent } from './spelen/eigen/eigen-competitie/eigen-competitie-speler/eigen-competitie-speler.component';
import { EigenCompetitieSchemaComponent } from './spelen/eigen/eigen-competitie/eigen-competitie-schema/eigen-competitie-schema.component';
import { EigenCompetitieMatchComponent } from './spelen/eigen/eigen-competitie/eigen-competitie-match/eigen-competitie-match.component';
import { EigenCompetitieLijstComponent } from './spelen/eigen/eigen-competitie/eigen-competitie-lijst/eigen-competitie-lijst.component';
import { EigenCompetitiePlanningComponent } from './spelen/eigen/eigen-competitie/eigen-competitie-planning/eigen-competitie-planning.component';
import { EigenCompetitieScorebordComponent } from './spelen/eigen/eigen-competitie/eigen-competitie-scorebord/eigen-competitie-scorebord.component';
import { WedScorebordComponent } from './spelen/wedstrijd/wed-scorebord/wed-scorebord.component';
import { KnbbTeamMatchScorebordComponent } from './spelen/knbb-team-match/knbb-team-match-scorebord/knbb-team-match-scorebord.component';
import { KnbbMatchScorebordComponent } from './spelen/knbb-match/knbb-match-scorebord/knbb-match-scorebord.component';
import { AnnonAantSpelersComponent } from './spelen/annon/annon-aant-spelers/annon-aant-spelers.component';
import { AnnonComponent } from './spelen/annon/annon.component';
import { AnnonSpelersComponent } from './spelen/annon/annon-spelers/annon-spelers.component';
import { AnnonScorebordComponent } from './spelen/annon/annon-scorebord/annon-scorebord.component';
import { EigenCompetitieWedsComponent } from './spelen/eigen/eigen-competitie/eigen-competitie-weds/eigen-competitie-weds.component';
import { BpTeamComponent } from './biljartpoint/bp-competitie-team/bp-team/bp-team.component';

export const routes: Routes = [
    { path: 'login', component: LoginComponent },
    { path: 'home', component: HomeComponent },
    { path: 'match/lijst/:wedNr', component: KnbbMatchLijstComponent },
    { path: 'match/lijst', component: KnbbMatchLijstComponent },
    { path: 'match/setup/spelers', component: KnbbMatchSetupComponent },
    { path: 'match/setup/comp', component: KnbbMatchCompComponent },
    { path: 'match/setup/check', component: KnbbMatchCheckComponent },
    { path: 'match/score', component: KnbbMatchScorebordComponent },
    { path: 'match', component: KnbbMatchComponent },
    { path: 'teammatch/lijst', component: KnbbTeamMatchLijstComponent },
    { path: 'teammatch/setup', children: [
        { path: 'thuis', component: KnbbTeamMatchSetupComponent },
        { path: 'gasten', component: KnbbTeamMatchSetupComponent }
    ]},
    { path: 'teammatch/setup/comp', component: KnbbTeamMatchCompComponent },
    { path: 'teammatch/setup/check', component: KnbbTeamMatchCheckComponent },
    { path: 'teammatch/score/:wedNr', component: KnbbTeamMatchScorebordComponent },
    { path: 'teammatch/:wedNr', component: KnbbTeamMatchComponent },
    { path: 'teammatch', component: KnbbTeamMatchComponent },
    { path: 'onderhoud/verenigingen/toevoegen', component: VerenigingAddComponent },
    { path: 'onderhoud/verenigingen/:verId/team/:teamId', component: VerenigingTeamComponent },
    { path: 'onderhoud/verenigingen/:verId/edit', component: VerenigingEditComponent },
    { path: 'onderhoud/verenigingen/:verId/spelers', component: SpelersComponent },
    { path: 'onderhoud/verenigingen/:verId', component: VerenigingComponent },
    { path: 'onderhoud/verenigingen', component: VerenigingenComponent },
    { path: 'onderhoud/lokaliteiten/:lokId', component: LokaliteitComponent },
    { path: 'onderhoud/lokaliteiten', component: LokaliteitenComponent },
    { path: 'onderhoud/spelers/toevoegen/:verId', component: SpelerComponent },
    { path: 'onderhoud/spelers/toevoegen', component: SpelerComponent },
    { path: 'onderhoud/spelers/:spelerId', component: SpelerComponent },
    { path: 'onderhoud/spelers', component: SpelersComponent },
    { path: 'onderhoud/knbbcompetities/toevoegen', component: KnbbCompetitieAddComponent },
    { path: 'onderhoud/knbbcompetities/:compId/teams', component: KnbbCompetitieEditTeamsComponent },
    { path: 'onderhoud/knbbcompetities/:compId', component: KnbbCompetitieEditComponent },
    { path: 'onderhoud/knbbcompetities', component: KnbbCompetitiesComponent },
    { path: 'onderhoud/moyennes/toevoegen', component: MoyenneTabelAddComponent },
    { path: 'onderhoud/moyennes/:klasse', component: MoyenneTabelEditComponent },
    { path: 'onderhoud/moyennes', component: MoyenneTabellenComponent },
    { path: 'onderhoud/districten', component: KnbbDistrictenComponent },
    { path: 'onderhoud/spelsoorten', component: SpelsoortenComponent },
    { path: 'onderhoud/eigencomps', component: CompetitiesComponent },
    { path: 'onderhoud/eigencomp', children: [
        { path: 'toevoegen', component: CompetitieComponent },
        { path: ':naam/spelers', component: CompSpelersComponent },
        { path: ':naam', component: CompetitieComponent }
    ]},
    { path: 'onderhoud', component: OnderhoudComponent },
    { path: 'config', component: ConfigComponent },
    { path: 'spelkeuze', component: SpelkeuzeComponent },
    { path: 'annon/aantspl', component: AnnonAantSpelersComponent },
    { path: 'annon/spelers', component: AnnonSpelersComponent },
    { path: 'annon/score', component: AnnonScorebordComponent },
    { path: 'annon', component: AnnonComponent },
    { path: 'wedstrijd/score', component: WedScorebordComponent },
    { path: 'wedstrijd/config', component: WedConfigComponent },
    { path: 'wedstrijd/lijst', component: WedLijstComponent },
    { path: 'wedstrijd/spelers', component: WedSpelersComponent },
    { path: 'wedstrijd/aantspl', component: WedAantSpelersComponent },
    { path: 'wedstrijd', component: WedstrijdComponent },
    { path: 'eigencomps/:naam/match/:ronde/:idxspl/:idxteg', component: EigenCompetitieMatchComponent },
    { path: 'eigencomps/:naam/score/:ronde/:idxspl/:idxteg', component: EigenCompetitieScorebordComponent },
    { path: 'eigencomps/:naam/lijst/:ronde/:idxspl/:idxteg', component: EigenCompetitieLijstComponent },
    { path: 'eigencomps/:naam/wedstrijden', component: EigenCompetitieWedsComponent },
    { path: 'eigencomps/:naam/schema/:ronde', component: EigenCompetitieSchemaComponent },
    { path: 'eigencomps/:naam/planning/:ronde', component: EigenCompetitiePlanningComponent },
    { path: 'eigencomps/:naam/:splId/:ronde', component: EigenCompetitieSpelerComponent },
    { path: 'eigencomps/:naam', component: EigenCompetitieComponent },
    { path: 'eigencomps', component: EigenCompetitiesComponent },
    { path: 'bpoint/home', component: BpHomeComponent },
    { path: 'bpoint/districten', component: BpDistrictenComponent },
    { path: 'bpoint/district', component: BpDistrictComponent },
    { path: 'bpoint/competitie', component: BpCompetitieComponent },
    { path: 'bpoint/competities', component: BpCompetitiesComponent },
    { path: 'bpoint/compteams', component: BpCompetitieTeamsComponent },
    { path: 'bpoint/lokaliteit', component: BpLokaliteitComponent },
    { path: 'bpoint/vereniging', component: BpVerenigingComponent },
    { path: 'bpoint/team', component: BpTeamComponent },
    { path: 'bpoint/spelers', component: BpSpelersComponent },
    { path: 'bpoint/moyennes', component: BpMoyennesComponent },
    { path: 'error/:condition', component: ErrorPageComponent },
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: '**', redirectTo: 'home', pathMatch: 'full' }
];
